In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print(arr)

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [ ]:
arr = np.array([[[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]]])
print(arr)
print("Dimention: ", arr.ndim)

[[[ 1  2  3  4  5]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]]
Dimention:  3


In [ ]:
arr = np.array([[[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]]])
print(arr[0,1,3])

8


In [ ]:
arr = np.array([1,2,3,4,5])
print(arr[2])
print(arr[-2])
print(arr[1]+arr[2])

3
4
5


In [ ]:
arr = np.array([1,2,3,4,5,6])
n= arr.reshape(2,3)
print(n)
print(n.ndim)

print(n[1,:2])

print(arr[3:])
print(arr[-5:-3])
print(arr[1:9:2])

[[1 2 3]
 [4 5 6]]
2
[4 5]
[4 5 6]
[2 3]
[2 4 6]


In [ ]:
arr = np.array([[[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]]])
print(arr.shape)
cpy= arr.copy()
#print(arr)
cpy[0, 2,2]=100
print(cpy)
arr[0, 2,2]=200
print(arr)
print(cpy)


(1, 3, 5)
[[[  1   2   3   4   5]
  [  5   6   7   8   9]
  [ 10  11 100  13  14]]]
[[[  1   2   3   4   5]
  [  5   6   7   8   9]
  [ 10  11 200  13  14]]]
[[[  1   2   3   4   5]
  [  5   6   7   8   9]
  [ 10  11 100  13  14]]]


In [ ]:
arr = np.array([[1,2,3,4,5],[5,6,7,8,9]])
for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
5
6
7
8
9


In [ ]:
arr = np.array([[[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]]])
for v in np.nditer(arr):
    print(v)

1
2
3
4
5
5
6
7
8
9
10
11
12
13
14


In [ ]:
arr = np.array([[[1,2,3,4,5],[5,6,7,8,9],[10,11,12,13,14]]])

x = np.where(arr == 4)
print(arr[x])

[4]


In [ ]:
v = arr.view()
print(v)
arr[0, 2,2]=200
print(arr)



[[[  1   2   3   4   5]
  [  5   6   7   8   9]
  [ 10  11 200  13  14]]]
[[[  1   2   3   4   5]
  [  5   6   7   8   9]
  [ 10  11 200  13  14]]]
